dua/urls.py
from django.urls import path

from . import views

app_name = 'dua'

urlpatterns = [
    path('buatJaDok', views.buatJadwalDokter, name = 'buatJadwalDokter'),
    path('createJaDok/<int:idx>', views.createJadwalDokter, name = 'createJadwalDokter'),
    path('showJaDok', views.showJadwalDokter, name = 'showJadwalDokter'),
    path('reserveDokter', views.tambahReservasi, name = 'tambahReservasi'),
    path('createReservasi/<int:idx>', views.createReservasi, name = 'createreservasi'),
    path('seeAppointment', views.seeMemeriksa, name = 'seeAppointment'),
    path('updateAppointment/<int:idx>', views.updateMemeriksa, name = 'updateAppointment'),
    path('deleteAppointment/<int:idx>', views.deleteMemeriksa, name = 'deleteAppointment'),
    path('buatRuangan', views.newRuangan, name = 'buatRuangan'),
    # path('buatBed', views.newBed, name = 'buatBed'),
]

lima/urls.py
from django.urls import path
from . import views

app_name='lima'

urlpatterns = [
    path('transaksi_makan/list_transaksi_makan/', views.listTransaksiMakan, name='listTransaksiMakan'),
    path('hotel/list_paket_makan/', views.listPaketMakan, name='listPaketMakan'),
    path('hotel/list_hotel/', views.listHotel, name='listHotel'),
    path('hotel/buat_hotel/', views.createHotel, name='createHotel'),
    path('hotel/update_hotel/<kode>', views.updateHotel, name='updateHotel'),
    path('transaksi_makan/detail_transaksi_makan/<idtransaksimakanan>', views.detailTransaksiMakan, name='detailTransaksiMakan'),
]

siruco_b14/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('siruco.urls')),
    path('satu/', include('satu.urls')),
    path('dua/', include('dua.urls')),
    path('tiga/',include('tiga.urls')),
    path('empat/',include('empat.urls')),
    path('lima/',include('lima.urls'))

]

lima/models.py
from django.db import models

# Create your models here.

lima/forms.py
from django import forms
from django.db import connection


class createHotelForm(forms.Form):
    attrs = {'class': 'form-control'}
    disabled_attrs = {'class': 'form-control', 'readonly':'readonly'}
    
    kode_hotel = forms.CharField(label="Kode Hotel", required=True, widget=forms.TextInput(attrs=disabled_attrs))
    nama = forms.CharField(label="Nama Hotel", required=True, widget=forms.TextInput(attrs=attrs))
    is_rujukan = forms.BooleanField(label="Rujukan", required=False, widget=forms.CheckboxInput(attrs=attrs))
    jalan = forms.CharField(label="Jalan", required=True, widget=forms.TextInput(attrs=attrs))
    kelurahan = forms.CharField(label="Kelurahan", required=True, widget=forms.TextInput(attrs=attrs))
    kecamatan = forms.CharField(label="Kecamatan", required=True, widget=forms.TextInput(attrs=attrs))
    kab_kot = forms.CharField(label="Kabupaten/Kota", required=True, widget=forms.TextInput(attrs=attrs))
    provinsi = forms.CharField(label="Provinsi", required=True, widget=forms.TextInput(attrs=attrs))

    def save(self, commit=True):

        kode = self.cleaned_data.get('kode_hotel')
        nama = self.cleaned_data.get('nama')
        is_rujukan = self.cleaned_data.get('is_rujukan')
        if is_rujukan == True:
            is_rujukan = "1"
        else:
            is_rujukan = "0"
        jalan = self.cleaned_data.get('jalan')
        kelurahan = self.cleaned_data.get('kelurahan')
        kecamatan = self.cleaned_data.get('kecamatan')
        kab_kot = self.cleaned_data.get('kab_kot')
        provinsi = self.cleaned_data.get('provinsi')
        
        with connection.cursor() as cursor:
            cursor.execute('insert into siruco.hotel values(%s, %s, %s, %s, %s, %s, %s, %s)', 
            [ 
                kode,
                nama,
                is_rujukan,
                jalan,
                kelurahan,
                kecamatan,
                kab_kot,
                provinsi
            ])

class updateHotelForm(forms.Form):
    def __init__(self, *args, **kwargs):
        kode = kwargs.pop('kode')
        super(updateHotelForm, self).__init__(*args, **kwargs)

        with connection.cursor() as cursor:
            cursor.execute('select * from siruco.hotel where kode = %s', [kode])
            
            hotel_object = cursor.fetchall()

            self.fields['kode_hotel'].initial = kode
            self.fields['nama'].initial = hotel_object[0][1]
            self.fields['is_rujukan'].initial = hotel_object[0][2]
            self.fields['jalan'].initial = hotel_object[0][3]
            self.fields['kelurahan'].initial = hotel_object[0][4]
            self.fields['kecamatan'].initial = hotel_object[0][5]
            self.fields['kab_kot'].initial = hotel_object[0][6]
            self.fields['provinsi'].initial = hotel_object[0][7]


    attrs = {'class': 'form-control'}
    disabled_attrs = {'class': 'form-control', 'readonly':'readonly'}

    kode_hotel = forms.CharField(label="Kode Hotel", required=True, widget=forms.TextInput(attrs=disabled_attrs))
    nama = forms.CharField(label="Nama Hotel", required=True, widget=forms.TextInput(attrs=attrs))
    is_rujukan = forms.BooleanField(label="Rujukan", required=False, widget=forms.CheckboxInput(attrs=attrs))
    jalan = forms.CharField(label="Jalan", required=True, widget=forms.TextInput(attrs=attrs))
    kelurahan = forms.CharField(label="Kelurahan", required=True, widget=forms.TextInput(attrs=attrs))
    kecamatan = forms.CharField(label="Kecamatan", required=True, widget=forms.TextInput(attrs=attrs))
    kab_kot = forms.CharField(label="Kabupaten/Kota", required=True, widget=forms.TextInput(attrs=attrs))
    provinsi = forms.CharField(label="Provinsi", required=True, widget=forms.TextInput(attrs=attrs))

    def save(self, commit=True):
        kode = self.cleaned_data.get('kode_hotel')
        nama = self.cleaned_data.get('nama')
        is_rujukan = self.cleaned_data.get('is_rujukan')
        if is_rujukan == True:
            is_rujukan = "1"
        else:
            is_rujukan = "0"
        jalan = self.cleaned_data.get('jalan')
        kelurahan = self.cleaned_data.get('kelurahan')
        kecamatan = self.cleaned_data.get('kecamatan')
        kab_kot = self.cleaned_data.get('kab_kot')
        provinsi = self.cleaned_data.get('provinsi')
        
        with connection.cursor() as cursor:
            cursor.execute('update siruco.hotel set nama = %s, isrujukan = %s, jalan = %s, kelurahan = %s, kecamatan = %s, kabkot = %s, prov = %s where hotel.kode = %s', 
            [ 
                nama,
                is_rujukan,
                jalan,
                kelurahan,
                kecamatan,
                kab_kot,
                provinsi,
                kode
            ])

lima/views.py
from django.shortcuts import render
from . import models
from django.db import connection
from django.shortcuts import redirect
from django.contrib.sessions.models import Session
from lima.forms import *

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def listTransaksiMakan(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.TRANSAKSI_MAKAN")
        row = dictfetchall(cursor)
        context = {
            "list_transaksi_makan": row,
            
        }
        return render(request, 'list_transaksi_makan.html', context)
    
    return render(request,"list_transaksi_makan.html",{})

def detailTransaksiMakan(request, idtransaksimakanan):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.TRANSAKSI_MAKAN AS TM WHERE TM.idTransaksiMakanan = %s", [idtransaksimakanan])
        row = dictfetchall(cursor)
        cursor.close()
        cursor.execute("SELECT * FROM SIRUCO.DAFTAR_PESAN AS DP JOIN SIRUCO.PAKET_MAKAN AS PM ON DP.KodePaket = PM.KodePaket WHERE DP.idTransaksiMakan = %s", [idtransaksimakanan])
        daftar_pesanan = dictfetchall(cursor)
        cursor.close()
        context = {
            "detail_transaksi_makan": row,
            "daftar_pesanan": daftar_pesanan,
        }
        return render(request, 'detail_transaksi_makan.html', context)
    
    return render(request,"detail_transaksi_makan.html",{})

def listPaketMakan(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.PAKET_MAKAN")
        row = dictfetchall(cursor)
        context = {
            "detail_paket_makan": row,
            
        }
        return render(request, 'list_paket_makan.html', context)
    
    return render(request,"list_paket_makan.html",{})

def listHotel(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.HOTEL")
        row = dictfetchall(cursor)
        context = {
            "hotel": row, 
        }
        # print(row)
        return render(request, 'list_hotel.html', context)
    
    return render(request,"list_hotel.html",{})

# Untuk mendapatkan kode hotel terakhir
def getKodeHotel():
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO SIRUCO")
        cursor.execute("SELECT kode FROM hotel ORDER BY kode DESC LIMIT 1")
        last = cursor.fetchall()[0][0]
        print(last)
        
        new = int(last[1:])+1
        kode_hotel = "1"+str(new).zfill(2)
    return kode_hotel

def createHotel(request):
    kode = getKodeHotel()
    # if request.session.has_key('role'):
    #     if request.session['role'] == 0:
    form = createHotelForm(initial={'kode_hotel' : kode},data=request.POST or None)
    response = {}
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('lima:listHotel')
        else: 
            return redirect('lima:listHotel')
    response.update(form=form)
    return render(request, 'create_hotel.html', response)
    # return redirect('homepage:homepage')
    

def updateHotel(request, kode):
    # if request.session.has_key('role'):
    #     if request.session['role'] == 0:
    form = updateHotelForm(kode=kode, data=request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('lima:listHotel')
        elif form.is_valid() == None:
            return redirect('lima:listHotel')
    response = {
        'form':form
    }
    return render(request, 'update_hotel.html', response)
    # return redirect('homepage:homepage')

lima/templates/create_hotel.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>List Hotel</title>
</head>
<body>
    <!--
    {% if request.session.role == 0 %}
    <div class="container">
        <div class="d-flex flex-column align-items-center my-5">
            <h4>Update Transaksi</h4>
            <form class="my-4" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <b>{{ field.label_tag }}</b>
                    {% if field.name == "waktu_pembayaran" %}
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        {{ form.waktu_pembayaran }}
                        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                    <script>
                        $(function () {
                        $("#datetimepicker1").datetimepicker({
                            format: 'DD/MM/YYYY HH:mm',
                        });
                        });
                    </script>
                    {% else %}
                    <div class="d-flex">
                        {{ field }}
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary pl-4 pr-4">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% else %}
        <div class="container" align="center" style="left: 50%; top: 45%; position: absolute;  transform: translate(-50%, -55%);">
            <h2>Maaf, halaman ini hanya untuk admin.</h2>
            <h4>Jika Anda merupakan admin, silahkan login sebagai admin.</h4>
            <h4>Terima kasih.</h4>
        </div>
    {% endif %}
    -->

    <div class="container">
        <div class="d-flex flex-column align-items-center my-5">
            <h1>Form Pembuatan Hotel</h1>
            <form class="my-4" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <b>{{ field.label_tag }}</b>
                    <div class="d-flex">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                <br>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary pl-4 pr-4">SIMPAN</button>
                </div>
            </form>
        </div>
    </div>

</body>
</html>

lima/templates/detail_transaksi_makan.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
</head>
<body>
    <div class="container">
        <h1 class="text-center header-big">DETAIL TRANSAKSI MAKAN</h1>
        <label><strong>Id Transaksi: </strong>{{ detail_transaksi_makan.idtransaksi }}</label>
        <br>
        <label><strong>Id Transaksi Makan: </strong>{{ detail_transaksi_makan.idtransaksimakanan }}</label>
        <br>
        <label><strong>Kode Hotel: </strong>{{ daftar_pesanan.kodehotel }}</label>  
	    <br>
	    <br>
        <table class="table table-bordered table-hover">
        <caption style="text-align: left;">Daftar Pesanan:</caption>
    </div>
  <thead>
    <tr>
      <th scope="col" class="text">Id Pesanan</th>
      <th scope="col" class="text">Paket Makan</th>
      <th scope="col" class="text">Harga</th>      
    </tr>
  </thead>
  <tbody>
    {% for pesanan in daftar_pesanan %}
    <tr>
        <th scope="row" class="text">{{ forloop.counter }}</th>
        <td class="text">{{ pesanan.kodepaket }}</td>
        <td class="text">{{ pesanan.harga }}</td> <!--gatau gmn cara ngambil harganya-->
        </tr>
    {% endfor %}
  </tbody>
</table>
    <label><strong>Total: </strong>Rp{{ detail_transaksi_makan.totalbayar }}</label> 
    <a href="{% url 'lima:listTransaksiMakan' %}">
        <button class="editbtn">Kembali</button>
    </a>
</body>
</html>

lima/templates/list_hotel.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>List Hotel</title>
</head>
<body>
    <h1>List Hotel</h1><br><br>
    <table style="width: 50%;">
        <thead>
        <tr>
            <th scope="col" class="text">No.</th>
            <th scope="col" class="text">Kode</th>
            <th scope="col" class="text">Hotel</th>
            <th scope="col" class="text">Rujukan</th>
            <th scope="col" class="text">Alamat</th>
            
            <th scope="col" class="text">Action</th>
            
        </tr>
        </thead>
    
        <tbody>
        {% for data_hotel in hotel %}
        <tr>
            <td scope="row" class="text" style="text-align: center;">{{ forloop.counter }}</td>
            <td class="text" style="text-align: center;">{{ data_hotel.kode }}</td>
            <td class="text" style="text-align: center;">{{ data_hotel.nama }}</td>
            {% if data_hotel.isrujukan == '1' %}
                <td class="text" style="text-align: center;"><input type="checkbox" checked disabled></td>
            {% else %}
                <td class="text" style="text-align: center;"><input type="checkbox" disabled></td>
            {% endif %}
            <td class="text" style="text-align: center;">{{ data_hotel.jalan }}, {{ data_hotel.kelurahan }}, {{ data_hotel.kecamatan }}, {{ data_hotel.kabkot }}, {{ data_hotel.prov }}</td>
            
            <td class="text" style="text-align: center;">
                <a href="{% url 'lima:updateHotel' kode=data_hotel.kode%}">
                    <button class="editbtn">Update</button>
                </a>
            </td>
            
        </tr>
        {% endfor %}
        </tbody>
    </table>

</body>
</html>

lima/templates/list_paket_makan.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>List Paket Makan</title>
</head>
<body>
    <h1>List Paket Makan</h1><br><br>
    <table style="width: 50%;">
        <thead>
        <tr>
            <th scope="col" class="text">No.</th>
            <th scope="col" class="text">Hotel</th>
            <th scope="col" class="text">Kode Paket</th>
            <th scope="col" class="text">Nama Paket</th>
            <th scope="col" class="text">Harga</th>
            <th scope="col" class="text">Action</th>
        </tr>
        </thead>
    
        <tbody>
        {% for paket_makan in detail_paket_makan %}
        <tr>
            <td scope="row" class="text" style="text-align: center;">{{ forloop.counter }}</td>
            <td class="text" style="text-align: center;">{{ paket_makan.kodehotel }}</td>
            <td class="text" style="text-align: center;">{{ paket_makan.kodepaket }}</td>
            <td class="text" style="text-align: center;">{{ paket_makan.nama }}</td>
            <td class="text" style="text-align: center;">{{ paket_makan.harga }}</td>
            <td class="text" style="text-align: center;">
                <a href="#">
                    <button class="editbtn">Detail</button>
                </a>  
                <a href="#">
                    <button class="editbtn">Update</button>
                </a>  
                <a href="#">
                    <button class="editbtn">Delete</button>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</body>
</html>

lima/templates/list_transaksi_makan.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>List Transaksi Makan dan Daftar Pesan</title>
</head>
<body>
    <h1>List Transaksi Makan dan Daftar Pesan</h1><br><br>
    <table style="width: 50%;">
        <thead>
        <tr>
            <th scope="col" class="text">No.</th>
            <th scope="col" class="text">Id Transaksi Hotel</th>
            <th scope="col" class="text">Id Transaksi</th>
            <th scope="col" class="text">Total Bayar</th>
            <th scope="col" class="text">Action</th>
        </tr>
        </thead>
    
        <tbody>
        {% for transaksi_makan in list_transaksi_makan %}
        <tr>
            <td scope="row" class="text" style="text-align: center;">{{ forloop.counter }}</td>
            <td class="text" style="text-align: center;">{{ transaksi_makan.idtransaksi }}</td>
            <td class="text" style="text-align: center;">{{ transaksi_makan.idtransaksimakanan }}</td>
            <td class="text" style="text-align: center;">{{ transaksi_makan.totalbayar }}</td>
            <td class="text" style="text-align: center;">
                <a href="{% url 'lima:detailTransaksiMakan' idtransaksimakanan=transaksi_makan.idtransaksimakanan %}">
                    <button class="editbtn">Detail</button>
                </a>  
                <a href="#">
                    <button class="editbtn">Update</button>
                </a>  
                <a href="#">
                    <button class="editbtn">Delete</button>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</body>
</html>

lima/templates/update_hotel.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Update Hotel</title>
</head>
<body>
    <div class="container">
        <div class="d-flex flex-column align-items-center my-5">
            <h1>Update Hotel</h1>
            <form class="my-4" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <b>{{ field.label_tag }}</b>
                    <div class="d-flex">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                <br>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary pl-4 pr-4">SIMPAN</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>